# Generated by Django 2.2.24 on 2023-01-10 06:27

from django.db import migrations


def gets_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230109_1656'),
    ]

    operations = [
        migrations.RunPython(gets_owners)
    ]
