# Generated by Django 2.2.24 on 2023-01-10 19:33

from django.db import migrations


def get_owner_apartments(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner_flats = Flat.objects.filter(id=owner.id)
        owner.apartments.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230110_0927'),
    ]

    operations = [
        migrations.RunPython(get_owner_apartments)
    ]
