# Generated by Django 2.2.24 on 2023-01-10 19:33

from django.db import migrations


def get_owner_apartments(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        owner_flats = Flat.objects.filter(owner=flat.owner)
        Owner.objects.filter(
            apartment_owner=flat.owner
        ).first().apartments_property.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230110_0927'),
    ]

    operations = [
        migrations.RunPython(get_owner_apartments)
    ]
